### ISSUE TITLE
ゲストログイン

### ISSUE THREAD

**Issue by quest-academia** [quest-academia/qa-rails-ec-training-rose#1]
就活などでサイトの中身を見せるために、ボタンひとつでログインできるようにしたい
参考：https://qiita.com/take18k_tech/items/35f9b5883f5be4c6e104

**Comment by yuzumotishun** [comment]
TODO：

 - [ ] SessionsControllerに新しいアクション`guest_login`を準備
 - [ ]  ゲストがメールアドレス・パスワードを変更できないようにusers#updateで条件分岐
 - [ ] 「ゲストログイン」のボタン配置（①ログイン画面の「ログイン」下、②ヘッダーの「ログイン」右）

予想対応時間: 6.0h
