### ISSUE TITLE
TOPページ画面

### ISSUE THREAD

**Issue by quest-academia** [quest-academia/qa-rails-ec-training-rose#10]
path: /
controller#action: StaticPages#home
参考モックアップ: home.html, home_after_login.html

ログインしているときとしていないときで表示画面を切り替えること。
リンク先が存在するものについては、リンクを設定すること。

ページが表示されたらスクリーンショットを保存し、ここに貼り付けて報告すること。

**Comment by yuzumotishun** [comment]
TODO：

- [ ]  StaticPagesコントローラ作成
- [ ] routesにrootとしてパス追加
- [ ]  viewでログインの有無で表示する画面と表示しない画面を条件分岐で分ける
- [ ] 「ログイン」・「新規登録」のボタンは実装段階でマージ済みならリンクを設定する。

予想対応時間: 2.5h

**Comment by yuki-tachi0219** [comment]
root_pathを設定しなければならないコントローラ・アクションがいくつかあった気がするので、そちらの対応もお願いいたします。

**Comment by yuzumotishun** [comment]
1. TOPページを作成し、ログインしているかどうかで条件分岐した画面が以下の画像になります。
1枚目...ログインしていない
2枚目...ログイン済み

2. 
> root_pathを設定しなければならないコントローラ・アクションがいくつかあった気がするので、そちらの対応もお願いいたします。

定義書やgrep等でroot_pathを設定する箇所を探したのですが、該当するのは僕が以前担当した「ゲストログイン」の他、未マージの「カート機能」・「ユーザー退会」での実装のようでした。そのため、ゲストログインでのTODOにおいては対応しましたが、その他は未対応です。

3.
> 「ログイン」・「新規登録」のボタンは実装段階でマージ済みならリンクを設定する。

ログインは対応しましたが、新規登録は「ユーザー登録ページ、新規登録」が未マージなのでTODOで残す方針です。

![スクリーンショット 2021-08-19 22 59 26](https://user-images.githubusercontent.com/78217764/130083030-811f5c43-c826-4aba-bf13-eca29f02aab0.png)
![スクリーンショット 2021-08-19 22 59 13](https://user-images.githubusercontent.com/78217764/130083035-41bf59c8-92d6-45da-8b50-d9b8853b3545.png)

**Comment by yuki-tachi0219** [comment]
ユーザー登録さっきマージしたので取り組んでください。
本当はroot_pathに遷移したいけど、しょうがないから別のパスを設定してるという箇所ありませんか？
認可処理のbefore_actionとか
