### ISSUE TITLE
商品検索画面(検索ロジック以外)

### ISSUE THREAD

**Issue by quest-academia** [quest-academia/qa-rails-ec-training-rose#11]
path: /products
controller#action: Products#index
参考モックアップ: products_index.html(商品がある場合),products_index_not_found.html(商品がない場合)

対応するコントローラとアクションを作成すること
参考モックアップをもとにhtml.erbファイルを作成すること。

検索機能は除き、最初から全商品が表示されている状態にすること。
ページネーション機能は、kaminari gemを使うこと。
参考：https://qiita.com/d_nagano1002/items/fd90340c50324e845fe1

ページが表示されたらスクリーンショットを保存し、ここに貼り付けて報告すること。

**Comment by ayumi0201** [comment]
- [ ] kaminari gemを導入
- [ ] products_controllerにindexアクションを追加
- [ ] viewにindex.html.erbを追加
- [ ] モックアップを参考に検索結果で商品がある場合と無い場合で表示を分岐させる
- [ ] 商品がある場合は、最初から全商品が表示されている状態にする
- [ ] 予想作業時間：５時間

**Comment by yuki-tachi0219** [comment]
OKです！そのまま進めていきましょー 🐧

**Comment by ayumi0201** [comment]
お疲れ様です。
products_controllerにindexアクションを追加、index.html.erbファイルを作成し全商品が表示されるよう実装し
kaminari gemを導入しページネーション機能も実装しております。
（ページネーション機能の表示がわかりやすいよう１ページ２件ずつ表示するようにしております）

以上、レビューの程宜しくお願い致します。

<img width="1440" alt="スクリーンショット 2021-07-23 22 58 48" src="https://user-images.githubusercontent.com/64362851/126792816-b57524cb-ad7e-411d-8b50-8f17128cb2f0.png">
<img width="1440" alt="スクリーンショット 2021-07-23 22 58 56" src="https://user-images.githubusercontent.com/64362851/126792857-aa121be7-e981-4e4b-a025-4b90957bca40.png">

**Comment by yuki-tachi0219** [comment]
いい感じだと思います。
- 1ページあたり何件表示するかは画面定義書に書いてあるので、プルリク前にその値に戻しておくこと
- ページネーションの見た目は、参考ページの「おまけ(ページネーションのカスタマイズ)」の章を見ながら修正すること
  - bootstrap5を導入しているが、`rails g kaminari:views bootstrap4`で大丈夫のはず

このあたりを済ませてからプルリクお願いします！
