### ISSUE TITLE
認可処理機能

### ISSUE THREAD

**Issue by quest-academia** [quest-academia/qa-rails-ec-training-rose#13]
ログインしていない場合、users#show, editページを見れないようにして自動的にログインページに遷移するよう、sessions_helper.rbに実装すること。
メソッド名はlogged_in_user
フラッシュメッセージは「ログインしてください。」

ログインしていたとしても、他人に関係するページは見れないようにして、自動的にroot_pathに遷移するよう、sessions_helper.rb に実装。
メソッド名はcorrect_user
フラッシュメッセージは「他人の情報にアクセスすることはできません。」

ページが表示されたらスクリーンショットを保存し、ここに貼り付けて報告すること。

**Comment by ayumi0201** [comment]
- [ ] 条件によってアクセス制限が掛かるようsessions_helper.rbに実装する
- [ ] ログアウト時 → users#show, editページを見れないようにして自動的にログインページに遷移するよう実装。
　　メソッド名はlogged_in_userとし、フラッシュメッセージは「ログインしてください。」
- [ ] ログイン時 → 他人に関係するページは見れないようにして、自動的にroot_pathに遷移するよう実装。
　　メソッド名はcorrect_userとし、フラッシュメッセージは「他人の情報にアクセスすることはできません。」
- [ ] ページが表示されたらスクリーンショットを保存し貼り付けて報告する。

**Comment by yuki-tachi0219** [comment]
注文詳細ページにも認可機能を付けたいです。
ログインした人の注文だけが見れるようにして、それ以外の注文は「他人の情報にアクセスすることはできません。」のメッセージを出したいです

**Comment by ayumi0201** [comment]
注文詳細ページにも認可機能を付けるようTODOを修正しました。

**Comment by ayumi0201** [comment]
お疲れ様です。
認可処理機能を実装しましたので表示ページのスクリーンショットを添付します。
このままプルリクさせて頂いてよろしいでしょうか。
ご確認宜しくお願い致します。

<img width="1440" alt="スクリーンショット 2021-08-13 19 36 44" src="https://user-images.githubusercontent.com/64362851/129345027-76505804-961b-4738-9e81-f2f0e7dbbeb9.png">
<img width="1440" alt="スクリーンショット 2021-08-13 19 37 14" src="https://user-images.githubusercontent.com/64362851/129345035-9a54a626-3d84-4326-a39a-9123d7134c2b.png">

**Comment by yuki-tachi0219** [comment]
良さそうな感じなので、そのままプルリクまでいきましょー
