### ISSUE TITLE
ログイン、ログアウト処理

### ISSUE THREAD

**Issue by quest-academia** [quest-academia/qa-rails-ec-training-rose#14]
ログイン: POST /login
ログアウト: DELETE /logout
ログイン後のリダイレクト先はユーザー詳細ページ
ログアウト後のリダイレクトはログインページ

ヘッダーにログアウトリンクを付けること

ログイン、ログアウト処理はHelperで定義すること。メソッド名はそれぞれlogin(user), logout

**Comment by ayumi0201** [comment]
- [ ] Rails チュートリアルなどを参考にログイン、ログアウト機能を実装する。
- [ ] sessionコントローラーを作成する（new、create、destroy）
- [ ] createアクション→ログイン、destroyアクション→ログアウトとなるように実装する。
- [ ] リダイレクト先をログイン後→ユーザー詳細ページ、ログアウト後→ログインページに設定
- [ ] before_actionを追加しログイン状態を確認してから動作するよう実装する。
- [ ] ルーティングを設定する。（ログイン: POST、ログアウト: DELETE）
- [ ] ログインページを作成（sessions.new.html.erb）
- [ ] sessionsヘルパーにログイン、ログアウト処理を定義する。メソッド名はlogin(user), logoutとする。
- [ ] 全ページに反映させる為Applicationコントローラーからsessions_helper.rbを読み込む設定を記載する。
- [ ] applicationコントローラーにlogged_in_userアクションを追加し全処理でログイン状態を確認してから動作するよう実装する。
- [ ] ヘッダーにログアウトリンクを記載する。
- [ ] 予想作業時間：２０時間

**Comment by yuki-tachi0219** [comment]
>before_actionを追加しログイン状態を確認してから動作するよう実装する。

>applicationコントローラーにlogged_in_userアクションを追加し全処理でログイン状態を確認してから動作するよう実装する。

> ヘッダーにログアウトリンクを記載する。

これらは別チケットで取り組みますので不要です。

**Comment by ayumi0201** [comment]
レビュー有難う御座います。
ご指摘箇所を削除しましたので作業に取り掛かります！
