### ISSUE TITLE
ログイン画面

### ISSUE THREAD

**Issue by quest-academia** [quest-academia/qa-rails-ec-training-rose#15]
path: /login
controller#action: Sessions#new
参考モックアップ: sessions_new.html

対応するコントローラとアクションを作成すること
参考モックアップをもとにhtml.erbファイルを作成すること。

画面が表示できたら、スクショを貼り付けること。
ログイン処理(ログインボタンを押したあとの処理)は実装不要

参考：https://qiita.com/d0ne1s/items/7c4d2be3f53e34a9dec7

**Comment by imai0602** [comment]
## To Do
 
- [ ] Session コントローラーの作成 (new、create、destroyアクションを持ったSessionsコントローラ)
- [ ] ルーティングの設定
- [ ] ログインページ (Sessions.new.html.erb)を作成 (form_withを使ってURLへのPOSTできるようにする）

予想工数 3h 

よろしくお願いします。

**Comment by imai0602** [comment]
ログイン画面の実装を行いましたのでご確認よろしくお願いします。

![image](https://user-images.githubusercontent.com/76435325/126990931-f93058a3-ea50-441e-beda-fc50e380fadc.png)

**Comment by yuki-tachi0219** [comment]
いい感じだと思います！
フッターのレイアウトが気になりますが、フッターの修正は別のissueで取り組むことになってましたよね？
ここでは気にしなくてもよさそうです。
