### ISSUE TITLE
エラーメッセージの日本語化

### ISSUE THREAD

**Issue by quest-academia** [quest-academia/qa-rails-ec-training-rose#16]
参考：https://qiita.com/Ushinji/items/242bfba84df7a5a67d5b

**Comment by yuzumotishun** [comment]
TODO：

 - [ ] gemfileに`rails-i18n`を追加
 - [ ]  `config/application.rb`に日本語対応用の一文追加
 - [ ] `config/locales/models/`に、`ja.yml`というファイルを作成し日本語対応表を作成
 - [ ] `config/application.rb`に読み込み用の一文を追加

予想対応時間: 2.5h

**Comment by yuki-tachi0219** [comment]
大丈夫だと思います！
