### ISSUE TITLE
ユーザー情報更新

### ISSUE THREAD

**Issue by quest-academia** [quest-academia/qa-rails-ec-training-rose#17]
アクション：Users#update
更新処理に成功したら ユーザー情報画面へ遷移、更新処理に失敗したら情報修正画面に戻り、エラーメッセージを表示させること

参考
- https://pikawaka.com/rails/update
- https://railstutorial.jp/chapters/updating_and_deleting_users?version=5.1#sec-updating_users

**Comment by imai0602** [comment]
## ToDo
- [ ]  users_controller.rbにupdateメソッド追加 
・分岐処理により更新成功の場合はredirect toでユーザー情報画面、失敗の場合はrenderを使用してエラーメッセージを表示。
・ストロングパラメーターの設定

- [ ] edit.html.erbの修正
・render処理に関する内容を記述する
・修正をクリックした後の処理を修正(form機能を使った記述に修正）

予想工数　4h

**Comment by yuki-tachi0219** [comment]
いい感じですね！そのまま進めていきましょう！
