### ISSUE TITLE
注文詳細画面

### ISSUE THREAD

**Issue by quest-academia** [quest-academia/qa-rails-ec-training-rose#18]
path: /orders/:id
controller#action: Orders#show
参考モックアップ: order_details.html, order_details2.html

URLで指定したidを持つ注文がある場合は、その注文の情報を表示(order_details.html)
注文が存在しない場合は、「該当の注文は見つかりませんでした」と表示(order_details2.html)

対応するコントローラとアクションを作成すること
参考モックアップをもとにhtml.erbファイルを作成すること。

ページが表示されたらスクリーンショットを保存し、ここに貼り付けて報告すること。

**Comment by yuzumotishun** [comment]
- [ ] routesにパスを指定
- [ ] orderコントローラーを作成
- [ ] モックアップのhtmlをviewに貼る
- [ ] コントローラーに必要なアクション(show)記述
- [ ] コントローラーに必要なメソッド(合計金額算出)記述
- [ ] viewで条件分岐

必要時間：10h

**Comment by yuki-tachi0219** [comment]
どういう条件分岐があるのか書いていただきたいです

**Comment by yuzumotishun** [comment]
以下、注文詳細画面のスクショになります。
１枚目がorderが存在している　&&　準備中が含まれているパターン
２枚目がorderが存在している　&&　準備中が含まれていないパターン
3枚目がorderが存在していないパターン
です。

![スクリーンショット 2021-07-26 1 29 44](https://user-images.githubusercontent.com/78217764/126906796-acbdb4e4-58c9-4bac-a94f-7685230f29e8.png)
![スクリーンショット 2021-07-26 1 29 36](https://user-images.githubusercontent.com/78217764/126906798-62ae6e4e-c135-4122-9885-151b17da0816.png)
![スクリーンショット 2021-07-26 1 32 02](https://user-images.githubusercontent.com/78217764/126906885-620482ec-0d62-44f7-a89b-c71514bf1d4c.png)

**Comment by yuki-tachi0219** [comment]
いい感じですね！
このままプルリクいきましょー
