### ISSUE TITLE
ユーザー情報修正画面

### ISSUE THREAD

**Issue by quest-academia** [quest-academia/qa-rails-ec-training-rose#19]
path: /users/:id/edit
controller#action: Users#edit
参考モックアップ: user_information_correction.html

対応するコントローラとアクションを作成すること
参考モックアップをもとにhtml.erbファイルを作成すること。
「修正」「退会」ボタンを押した後の機能は実装不要

ページが表示されたらスクリーンショットを保存し、ここに貼り付けて報告すること。

**Comment by imai0602** [comment]
ざっくりですが以下のような手順を考えております。

- [ ] users コントローラーにedit アクションを追加
- [ ] edit.html.erb を作成
- [ ] ルーティングの確認（必要あればroute.rbを修正）
- [ ] 参考モックアップを参考にedit.html.erb を修正して、editアクションで取得したユーザー情報を表示させる

予想工数：6h

**Comment by yuki-tachi0219** [comment]
問題なさそうなので、このまま進めていただければと思います✨

**Comment by imai0602** [comment]
ユーザー情報修正画面の作成を行いましたのでまずはスクショの確認をお願いします！

![image](https://user-images.githubusercontent.com/76435325/126502035-c210542b-37bc-4fc6-b315-5ca755282678.png)
![image](https://user-images.githubusercontent.com/76435325/126502100-2680d471-774d-4964-86d6-f99229a443b1.png)

**Comment by yuki-tachi0219** [comment]
問題なさそうなので、プルリク提出お願いします！まずは太田さんに見てもらいましょうか。
