### ISSUE TITLE
エラーメッセージの表示

### ISSUE THREAD

**Issue by quest-academia** [quest-academia/qa-rails-ec-training-rose#2]
ユーザー登録やユーザー情報更新でバリデーションエラーが起きた時に、どんなバリデーションエラーが出たか表示すること
参考：https://qiita.com/d0ne1s/items/25acf0e70c12042c4c35

**Comment by yuzumotishun** [comment]
TODO：

 - [ ] viewにsharedフォルダを作り、その中に`error_messages.html.erb`を作成
 - [ ] 上のファイル内でエラーメッセージを呼び出すerbを記述
 - [ ] users/editのerbのフォームの中に`<%= render 'shared/error_messages', object: f.object %>`と書き込み
 - [ ] 情報を修正し、反映確認
 - [ ] プルリク提出

予想対応時間: 1.5h

**Comment by yuki-tachi0219** [comment]
OKです！そのまま進めていただければと思います。

**Comment by yuzumotishun** [comment]
画像のように、情報修正画面で日本語表記に対応していることを確認致しました。
また、`password_confirmation`（一枚目青ハイライト部分）に関しては英語のままだったので、`ja.yml`のuserモデルのカラム欄に並列して追記致し、「パスワード（再入力）」としました。
![スクリーンショット 2021-08-11 21 08 30](https://user-images.githubusercontent.com/78217764/129029892-783dc8d0-8f53-4523-82ce-16b3bc324859.png)
![スクリーンショット 2021-08-11 21 07 01](https://user-images.githubusercontent.com/78217764/129029899-38fa6ee3-c6d1-4cc8-905d-e7c4436fcfea.png)

**Comment by TAKO-zhangyu** [comment]
よいと思います！ありがとうございます！

**Comment by yuki-tachi0219** [comment]
エラーメッセージを「ユーザー情報修正」の上に持っていきたいです。
エラーメッセージの箇所もフラッシュメッセージを同じく赤背景赤文字にできますでしょうか 🙏
