### ISSUE TITLE
商品詳細画面

### ISSUE THREAD

**Issue by quest-academia** [quest-academia/qa-rails-ec-training-rose#20]
path: /products/:id
controller#action: Products#show
参考モックアップ: products_show.html, products_show_not_found.html

URLで指定したidを持つ商品がある場合は、その商品の情報を表示(products_show.html)
商品が存在しない場合は、「該当商品が見つかりませんでした」と表示(products_show_not_found.html)

対応するコントローラとアクションを作成すること
参考モックアップをもとにhtml.erbファイルを作成すること。

ページが表示されたらスクリーンショットを保存し、ここに貼り付けて報告すること。

**Comment by ayumi0201** [comment]
- [ ] Productコントローラーを作成、showアクションを追加する。
- [ ] 参考モックアップをもとにhtml.erbファイルを作成する。
- [ ] コントローラーにコーディングし
　- URLで指定したidを持つ商品がある場合は、その商品の情報をproduct_details.htmlに表示。
　- 商品が存在しない場合は、「該当商品が見つかりませんでした」とproduct_details2.htmlに表示
- [ ] ページが表示されたらスクリーンショットを貼り付けて報告する。
- [ ] 作業予想時間：10時間

**Comment by yuki-tachi0219** [comment]
チェックリストいい感じです！このまま進めてみましょー

**Comment by ayumi0201** [comment]
コンフリクトを解消しましたのでご確認をお願い致します。
https://github.com/quest-academia/qa-rails-ec-training-rose/commit/10fa3c1fce2b8f6714de528b0a902c86fc7b2a97
