### ISSUE TITLE
htmlファイルの共通化

### ISSUE THREAD

**Issue by quest-academia** [quest-academia/qa-rails-ec-training-rose#21]
```
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" 
     ...
```
このタグをlayouts/application.html.erbのheadタグの中に移すこと。
CSSを定義しているstyleタグもlayouts/application.html.erbのheadタグの中に移すこと。
headerタグについては、`app/views/layouts/_header.html.erb`という新しいファイル(部分テンプレート)を作成しそこに移すこと。
footerタグについては、`app/views/layouts/_footer.html.erb`という新しいファイル(部分テンプレート)を作成しそこに移すこと。
headタグも部分テンプレート化したい

参考：
https://www.javadrive.jp/rails/template/index4.html

**Comment by ayumi0201** [comment]
- [ ] 説明文のlinkタグをそのままコピーしlayouts/application.html.erbのheadタグの中に記載する。
- [ ] 各viewファイル記載のheadタグをtitle以外layouts/application.html.erbのheadタグの中に移す。
- [ ] headerタグは、app/views/layouts/_header.html.erbという新しいファイル(部分テンプレート)を作成しそこに移すこと。
- [ ] footerタグは、app/views/layouts/_footer.html.erbという新しいファイル(部分テンプレート)を作成しそこに移すこと。
- [ ] 各viewファイルにrenderメソッドを記載し部分テンプレートが適用されているか確認する。
- [ ] 作業予想時間：１時間
