### ISSUE TITLE
セキュアなパスワードの実装

### ISSUE THREAD

**Issue by quest-academia** [quest-academia/qa-rails-ec-training-rose#23]
パスワードを保存する際にハッシュ化を使うことで、より安全にパスワードをDBに保管できるようにすること。
パスワードカラムの名前を変更しなければならないので注意。
seedを実行してからrails console でユーザーの情報を表示させ、ハッシュ化されたパスワードが表示されるか確認すること。
↑
スクショの貼り付けは不要
参考サイト：https://qiita.com/kents1002/items/3015d60b91e6b03d5ffa

**Comment by ayumi0201** [comment]
- [ ] user.rbに "has_secure_password" を記述する
- [ ] passwordカラムをpassword_digestカラムに変更する為マイグレーションファイルとseeds.rbを修正する
- [ ] Gemfileに "gem 'bcrypt', '3.1.13'" を記述する
- [ ] docker起動中に "docker-compose exec web bundle install" を実行しGemをインストール
- [ ] "rails db:seed" を実行後コンソール上でユーザーの情報を表示しハッシュ化されたパスワードが表示されるか確認すること
- [ ] 作業予想時間：１時間
