### ISSUE TITLE
ユーザー情報画面

### ISSUE THREAD

**Issue by quest-academia** [quest-academia/qa-rails-ec-training-rose#24]
path: /users/:id
controller#action: Users#show
参考モックアップ: users_show.html

対応するコントローラとアクションを作成すること
参考モックアップをもとにhtml.erbファイルを作成すること

ページが表示されたらスクリーンショットを保存し、ここに貼り付けて報告すること。

**Comment by imai0602** [comment]
モックアップの画面から必要な機能を推定し、以下のような作業が必要であると考えましたが
必要な作業が網羅できるているか不安です。恐れ入りますがアドバイス頂きたくお願いします！

【考えた必要な機能】
１. 既にログインして（登録されている）ユーザーのデータを取得して、表示する。
２.取得したデータの編集・削除機能を実装し、保存する。（編集・削除用の画面も設計する）
３.編集・削除が完了したことをユーザーに向けて表示する

【考えた作業の流れ】
① rails gでUsersコントローラーファイルとビューファイルを作成
② コントローラファイルの編集　⇨ User.all などでデータを引っ張ってくる記述を記載
③ アクションの作成　⇨ showアクションを設定し、User情報を引っ張ってくる
④ ルーティングの設定　⇨ showアクションに関する記述、CRUD処理に関する技術を行う
⑤ html.erbファイルの編集　⇨ レイアウト調整、link to の設定など

以上、よろしくお願いします！

**Comment by TAKO-zhangyu** [comment]
@imai0602 
お疲れ様です！
以下は不要です！

> ２.取得したデータの編集・削除機能を実装し、保存する。（編集・削除用の画面も設計する）
> ３.編集・削除が完了したことをユーザーに向けて表示する

それ以外はよいと思います！
