### ISSUE TITLE
bootstrap gem 導入・cssファイルの切り出し

### ISSUE THREAD

**Issue by quest-academia** [quest-academia/qa-rails-ec-training-rose#25]
bootstrap gemを導入する。
htmlファイルに直接書いているcssを別ファイルに切り出す。切り出し先はapplication.scss

bootstrap gemの導入の際はバージョン指定に気をつけること

**Comment by yuzumotishun** [comment]
- [ ] Bootstrap 5.0.2（最新）のgemを追加
- [ ] ユーザー情報画面のCSSをassets/stylesheets/custom.scss に切り出す
- [ ] assets/stylesheets/application.scssに@import "bootstrap"; を追記

予想完了時間 30min

**Comment by TAKO-zhangyu** [comment]
> ユーザー情報画面のCSSをassets/stylesheets/custom.scss に切り出す

現時点で画面があるのはユーザー情報画面だけだと思いますが、他にも画面が増えた場合はそちらもお願いいたします！

**Comment by TAKO-zhangyu** [comment]
>  Bootstrap 5.0.2（最新）のgemを追加
一旦、5.0.0にしていただきたいです！
今ユーザー情報詳細画面などで使用しているbootstrapが5.0.0を使用しているようなので、それに合わせて5.0.0でお願いいたします！

（正確には5.0.0.beta3のようですが、調べた限り5.0.0が後続なようなのでこれでよいと思います）
https://rubygems.org/gems/bootstrap/versions/5.0.0.beta3
