### ISSUE TITLE
データ投入 Seed Products関連

### ISSUE THREAD

**Issue by quest-academia** [quest-academia/qa-rails-ec-training-rose#28]
db/seeds.rb にProduct関係の仮データを入れること

2人のユーザーに対して2つずつProductを作成すること。
seedを実行することで、合計4つのProductが生成されるようにすること。
カテゴリ、販売状態、商品状態はそれぞれ2つ生成し、Productに紐付けること。
仕入は生成する必要なし。

コンソール上で
rails db:seed
を実行して、rails console上でデータが正しく作られたかどうか確認する。

rails console上で Product.all を実行 → Product一覧が出てくる。これをスクショして添付すること。

**Comment by ayumi0201** [comment]
- [ ] db/seeds.rb にProduct関係の仮データを入れる。
- [ ] 2人のユーザーに対して2つずつProductを作成し合計4つのProductを生成する。
- [ ] カテゴリ、販売状態、商品状態はそれぞれ2つ生成し、Productに紐付ける（仕入れは生成不要）
- [ ] コンソール上でrails db:seedを実行、データが正しく作られたかどうか確認する。
- [ ] rails console上で Product.all を実行 → Product一覧が出てくる。これをスクショし添付。
- [ ] 作業予想時間：３時間

**Comment by yuki-tachi0219** [comment]
方針は問題なさそうなので、このまま進めていただければと思います

**Comment by ayumi0201** [comment]
お疲れ様です。
今井さん担当のUsersがレビュー完了後にrails db:seed実行になるかと思いますので
記載方法が間違っていないかどうかseeds.rbスクショを添付しますので先にご確認頂くことは可能でしょうか。
お手数ですが宜しく御願い致します。
<img width="1440" alt="スクリーンショット 2021-07-11 19 15 09" src="https://user-images.githubusercontent.com/64362851/125191424-5765a280-e27d-11eb-9a79-e6938077b2f6.png">

**Comment by yuki-tachi0219** [comment]
軽くレビューいたします。
```
[
  ['販売中'],
  ['欠品中']
].each do....
```
のように二重配列が定義されていますが、これだとエラーが起きると思います。
each内で
`{ sale_status_name: ['販売中'] }`
のように値が入ってしまうからです。`['販売中', '欠品中'].each do ...`のような感じで配列を定義すればだいじょうぶですよ。

**Comment by yuki-tachi0219** [comment]
あと、このProductの作り方だと、
1人目のユーザーも2人目のユーザーも同じ名前や値段の商品を持つことになってしまうので、
名前の異なる4つの商品を作って、そのうち2つを1人目に、残り2つを2人目のユーザーに紐付けたいですね。

**Comment by ayumi0201** [comment]
レビュー有難う御座います。
ご指摘通り二重配列を修正しました。
Productについては１人に２つずつ異なる商品を持つよう修正しました。
> user_id : 1 (2)
↑のようにuser_idを指定し記載しましたが記載方法は合っていますでしょうか。
お手数ですがご確認の程宜しく御願い致します。
<img width="1440" alt="スクリーンショット 2021-07-11 21 49 13" src="https://user-images.githubusercontent.com/64362851/125195780-280d6080-e292-11eb-9818-003e945ca65b.png">

**Comment by yuki-tachi0219** [comment]
いい感じだと思います！
今井さんのブランチからUserデータ投入のコマンドをパクってくれば上記コードの挙動を確認できると思うので、やってみてください！

**Comment by ayumi0201** [comment]
お疲れ様です。
先程は遅い時間まで有難う御座いました🙇‍♀️
seeds.rbを修正しました。
先程同様Validationのエラーが出ておりrails db:seedが実行出来ないのですが
一度Pushしてしまった方が宜しいのでしょうか。
以上、ご確認の程宜しく御願い致します。

<img width="1440" alt="スクリーンショット 2021-07-13 0 34 05" src="https://user-images.githubusercontent.com/64362851/125315451-1b603980-e372-11eb-8664-3825e7b8b5c8.png">
<img width="1440" alt="スクリーンショット 2021-07-13 0 34 15" src="https://user-images.githubusercontent.com/64362851/125315457-1dc29380-e372-11eb-8065-1f9e6ad65706.png">
<img width="1440" alt="スクリーンショット 2021-07-13 0 34 25" src="https://user-images.githubusercontent.com/64362851/125315466-21561a80-e372-11eb-9176-86954391b285.png">

**Comment by yuki-tachi0219** [comment]
ご報告ありがとうございます。一旦pushはやめておいて、Slackでエラー内容についてご質問をいただけますでしょうか。

**Comment by ayumi0201** [comment]
rails console上で Product.all を実行しProduct一覧が表示される事を確認しましたので
ご確認宜しくお願い致します。(Category, SaleStatus, ProductStatusについても確認済みです)
<img width="1440" alt="スクリーンショット 2021-07-13 22 01 50" src="https://user-images.githubusercontent.com/64362851/125456131-8d7a3eaa-ef96-4741-a676-a5841da33831.png">

**Comment by yuki-tachi0219** [comment]
Seedうまくいってそうなので、
そのままプルリク出していいですよー
