### ISSUE TITLE
データ投入 Seed Users関連

### ISSUE THREAD

**Issue by quest-academia** [quest-academia/qa-rails-ec-training-rose#29]
db/seeds.rb にUserの仮データを入れること

2人のユーザーを作成すること。Email, Passwordは今後何度も使用するため、覚えやすいシンプルなものにすること。
UserClassificationオブジェクトは1種類でOK

コンソール上で
rails db:seed
を実行して、rails console上でデータが正しく作られたかどうか確認する。

rails console上で User.all を実行 → User一覧が出てくる。これをスクショして添付すること。

**Comment by imai0602** [comment]
- [ ] db/seeds.rbの編集　(.createメソッドでユーザーを２人のユーザーと UserClassificationオブジェクトを1種類作成。.saveメソッドで保存）
- [ ] rails db:seed　を実行して、正しくデータが投入されているか確認する。
- [ ] rails console上で User.all を実行 ⇨ スクショ

予想完了時間 (手戻りこみ）3時間

ほぼ、課題説明欄に書いてあることと同じですが以上の手順で進めたいと思います！

**Comment by imai0602** [comment]
rails console上で User.all (UserClassification.all) を実行して一覧を確認しましたのでご確認願います！

![image](https://user-images.githubusercontent.com/76435325/125170623-c5ad5500-e1ea-11eb-9876-04a81fa140db.png)

**Comment by yuki-tachi0219** [comment]
@imai0602 
ユーザーがちゃんと作成されていますね ✨ 
このままプルリク提出お願いします！
細かい指摘についてはプルリク内でお伝えします。
