### ISSUE TITLE
カート機能

### ISSUE THREAD

**Issue by quest-academia** [quest-academia/qa-rails-ec-training-rose#3]
カートページ
path: POST carts/add_cart
controller#action: carts#show,
参考モックアップ: cart_list.html

削除処理
path: DELETE carts/destroy
controller#action: Users#create

カートへ商品を追加、削除する機能を実装。

注文確定のボタン押下後、注文情報をDBへ格納し、購入画面へ遷移

sessionを使用した実装にすること。

**Comment by ayumi0201** [comment]
TODO：
- [ ] sessionを使用しカート機能を実装
- [ ] cartコントローラーを作成(showのみ)
- [ ] 商品詳細ページとcartsコントローラのadd_cartメソッドでカートが空の場合、同じ商品が入っている場合で表示を分岐させる。
- [ ] cartコントローラーでカート内商品一覧ページを表示する。(参考モックアップ: cart_list.html)
- [ ] cartコントローラーでカート内商品の数量変更(change_quantityメソッド)、商品削除(destroy_carts_itemメソッド)ができるようにする。
- [ ] 数量変更と商品削除はそれぞれmethodが違うのでそれぞれ別のルーティングを設定する。
- [ ] ordersコントローラのcreate、clearメソッドでカート内商品一覧ページ「注文を確定する」ボタンを押下でカート内を空にして購入完了画面を表示する。(参考モックアップ: purchase_completed.html)
- [ ] clearメソッドが動いた後購入完了画面にリダイレクトし注文番号を表示する。
- [ ] 予想作業時間：20時間
- [ ] 参考ページ：https://qiita.com/sashun/items/5e36e794daa1a61b5ed2

**Comment by yuki-tachi0219** [comment]
問題なさそうなので、そのまま進めてください 👍
