### ISSUE TITLE
Validation Users関連

### ISSUE THREAD

**Issue by quest-academia** [quest-academia/qa-rails-ec-training-rose#30]
画面定義書に記載されているバリデーション項目に従って、Validationを定義する。

バリデーションは、画面定義書を参考にすること
対象テーブル: User, UserClassification

**Comment by yuzumotishun** [comment]
TODO

- [ ] 画面定義書を確認し、カラムごとのvaridation確認
- [ ] app/modelsにvalidation記載
- [ ]  コンソール上で効いているか確認
- [ ] プルリク

予想完了時間 ３時間
