### ISSUE TITLE
DB構築 Migration Products関連

### ISSUE THREAD

**Issue by quest-academia** [quest-academia/qa-rails-ec-training-rose#32]
migrationファイルを作って、DB構造を決める
rails db:migrate を実行して、db/schema.rbを作成すること
DB構造は、GoogleドライブのER図を参考にすること
対象はProducts関連の合計5テーブル。

データ型の読み方はこちら
https://qiita.com/vermilionfog/items/816fa7de1d0213979929#対応表

db/schema.rb のProductに関する部分をスクショして添付すること

**Comment by ayumi0201** [comment]
- [ ] products関連のテーブルを５つ作成。
 - [ ] rails db:migrate を実行しdb/schema.rbを作成
 - [ ] 作業予想時間：３時間

**Comment by ayumi0201** [comment]
お疲れ様です。
製品関連のテーブルを５つ作成しましたのでレビュー宜しく御願い致します。
<img width="1440" alt="スクリーンショット 2021-07-08 11 42 02" src="https://user-images.githubusercontent.com/64362851/124854231-071ee400-dfe2-11eb-9434-25be48701ea7.png">

**Comment by yuki-tachi0219** [comment]
必要なテーブルすべてできているっぽいので、このままプルリクに進みましょう！
