### ISSUE TITLE
DB構築 Migration Users関連

### ISSUE THREAD

**Issue by quest-academia** [quest-academia/qa-rails-ec-training-rose#33]
migrationファイルを作って、DB構造を決める
rails db:migrate を実行して、db/schema.rbを作成すること
DB構造は、GoogleドライブのER図を参考にすること

データ型の読み方はこちら
https://qiita.com/vermilionfog/items/816fa7de1d0213979929#対応表

db/schema.rb のUserに関する部分をスクショして添付すること

**Comment by imai0602** [comment]
rails db:migrate を実行して、db/schema.rbを作成いたしましたのでご確認願います

![image](https://user-images.githubusercontent.com/76435325/124487270-767db380-dde9-11eb-83dd-644ba3b3d2e8.png)

**Comment by yuki-tachi0219** [comment]
UserClassificationモデルの構築もお願いします 🙏

**Comment by imai0602** [comment]
対応遅くなり申し訳ございません。承知致しました今から作業させていただきます！

**Comment by imai0602** [comment]
UserClassificationを追加して、Users テーブルに外部キーの追加を行いました。
https://github.com/quest-academia/qa-rails-ec-training-rose/issues/33

![image](https://user-images.githubusercontent.com/76435325/124634951-da73ab00-dec1-11eb-8f71-90e42a59afaa.png)

**Comment by yuki-tachi0219** [comment]
ご報告ありがとうございます。このままプルリクの作成お願いします 🐧
