### ISSUE TITLE
環境構築(Ayumiさん)

### ISSUE THREAD

**Issue by quest-academia** [quest-academia/qa-rails-ec-training-rose#37]
※プルリク不要
localhost:3000にアクセスして、「Yeh! You're on Rails!!」が表示されればOK
このissueに、「Yeh! You're on Rails!!」の画面をスクショして添付すること。
M1のMacの場合はローカル環境で構築、それ以外の場合はdockerを用いて環境構築すること。

**Comment by ayumi0201** [comment]
dockerの環境構築が完了しましたのでレビュー宜しくお願いします。

<img width="1129" alt="スクリーンショット 2021-07-04 23 20 34" src="https://user-images.githubusercontent.com/64362851/124388657-c3e11e80-dd1e-11eb-8666-7c6465cd3f92.png">

**Comment by yuki-tachi0219** [comment]
OKです！これで完了とさせていただきます！
