### ISSUE TITLE
環境構築(今井さん)

### ISSUE THREAD

**Issue by quest-academia** [quest-academia/qa-rails-ec-training-rose#38]
※プルリク不要
localhost:3000にアクセスして、「Yeh! You're on Rails!!」が表示されればOK
このissueに、「Yeh! You're on Rails!!」の画面をスクショして添付すること。
M1のMacの場合はローカル環境で構築、それ以外の場合はdockerを用いて環境構築すること。

**Comment by imai0602** [comment]
![image](https://user-images.githubusercontent.com/76435325/124378328-b2325380-dceb-11eb-8ebd-3a29e2519a3e.png)

ドッカーの環境構築を行いましたのでご確認よろしくお願いします

**Comment by yuki-tachi0219** [comment]
OKです！これで完了とさせていただきます！
