### ISSUE TITLE
環境構築(シュンさん)

### ISSUE THREAD

**Issue by quest-academia** [quest-academia/qa-rails-ec-training-rose#39]
※プルリク不要
localhost:3000にアクセスして、「Yeh! You're on Rails!!」が表示されればOK
このissueに、「Yeh! You're on Rails!!」の画面をスクショして添付すること。
M1のMacの場合はローカル環境で構築、それ以外の場合はdockerを用いて環境構築すること。

**Comment by yuzumotishun** [comment]
「Yeh! You're on Rails!!」を表示できました！
![スクリーンショット 2021-07-05 0 14 23](https://user-images.githubusercontent.com/78217764/124390366-36a1c800-dd26-11eb-9178-26d211f69220.png)

**Comment by yuki-tachi0219** [comment]
OKです！これで完了とさせていただきます！！
