### ISSUE TITLE
注文履歴

### ISSUE THREAD

**Issue by quest-academia** [quest-academia/qa-rails-ec-training-rose#5]
path: /orders
controller#action: Orders#index
参考モックアップ: order_history.html, order_history_no_exit.html

対応するコントローラとアクションを作成すること
参考モックアップをもとにhtml.erbファイルを作成すること。
「直近3か月の注文を表示｣ボタンは実装しない
注文が存在しない場合の画面も、画面定義書参照のこと。

ページネーション機能は、kaminari gemを使うこと。

**Comment by imai0602** [comment]
## ToDo

- [ ] orders_controllerにindexアクションを追加
・注文履歴のDBから取り出す機能を実装

- [ ] orders/viewにindex.html.erbを追加（モックアップを参考に作成する） 

・注文履歴がある場合と無い場合で条件分岐を行い、画面を表示させる
if : そのユーザーに注文履歴がある場合は、 取り出した注文履歴データを表示させる。
else :  注文履歴が存在しない場合は、存在しない用の画面を表示させる

- [ ] kaminari gemを使いページネーション機能実装

予想作業時間：10時間

**Comment by yuki-tachi0219** [comment]
「１件でも『注文状態：準備中』のものがあれば...」という条件分岐も画面定義書にあったとおもうので確認お願いします

**Comment by imai0602** [comment]
大変失礼しました。以下に修正します。

- [ ] orders_controllerにindexアクションを追加

・注文履歴のDBから取り出す機能を実装

 

- [ ] orders/viewにindex.html.erbを追加（モックアップを参考に作成する）

・注文履歴がある場合と無い場合で条件分岐を行い、画面を表示させる
if : そのユーザーに注文履歴がある場合は、 取り出した注文履歴データを表示させる。
else : 注文履歴が存在しない場合は、存在しない用の画面を表示させる

・注文履歴一覧のソートは注文日時：降順で表示させる

・注文状態が準備中の商品 が有る場合と無い場合で条件分岐を行う。
if：ある場合は備考に 「注文状態：準備中」を表示
else ：ない場合は備考に 「注文状態：発送済」を表示

- [ ]  kaminari gemを使いページネーション機能実装

予想作業時間：12時間

**Comment by yuki-tachi0219** [comment]
OKです！これだけ洗い出せていれば実装がスムーズですね。
商品一覧ページでkaminari gemによるページネーションが実装されているので、それもパクっていただければと思います。
