### ISSUE TITLE
商品検索画面(検索ロジック)

### ISSUE THREAD

**Issue by quest-academia** [quest-academia/qa-rails-ec-training-rose#6]
参考：https://qiita.com/yusuko/items/cff4e46aeafbc3beecf2
商品の商品名カラムに対して部分一致の検索をかけること。
検索キーワードがないときは、全商品を表示させること。

**Comment by yuzumotishun** [comment]
TODO:

- [ ] 検索ボタン周りにform_withを適用
- [ ] コントローラでViewから渡されたパラメータ(params[:search])を取得し、モデルへ渡す。
- [ ] モデルでsearchメソッドを定義(whereメソッドで条件に合うものをすべて取得)
- [ ] paramsの有無で「一致した商品表示」or 「全商品表示」の条件分岐
- [ ] viewに出力してeachメソッドで条件にあった商品群を一覧表示

予想完了時間: 10時間

**Comment by yuki-tachi0219** [comment]
>paramsの有無で「一致した商品表示」or 「全商品表示」の条件分岐

こちらは、モデルのsearchメソッドの中で実装してみて下さい。

**Comment by yuzumotishun** [comment]
コンフリクトを解消致しました。ご確認お願いします。
https://github.com/quest-academia/qa-rails-ec-training-rose/commit/95d84a3db35f3efa751fb751e28d9580510f4539
