### ISSUE TITLE
ユーザー退会

### ISSUE THREAD

**Issue by quest-academia** [quest-academia/qa-rails-ec-training-rose#7]
path: DELETE /users/:id
controller#action: users#destroy
退会をボタンを押したら、
「ユーザーデータが全て削除されます。本当に退会しますか？」
というダイアログボックスが開くようにすること

退会後、トップページに遷移すること
自動的にログアウト状態になっているか確認すること。

**Comment by imai0602** [comment]
## ToDo

- [ ] `users_controller.rb`に`destroy` アクションを追加。
- ログインしているユーザーの情報を取得して、ユーザー情報の物理削除を行う。
- 退会完了後に、トップページへリダイレクト。(TOPページが完了次第、実装する。）

- [ ] `users/edit.html`の修正
- 退会ボタンを`form_with`を使った書き方に修正
-  `data: { confirm: ` を使って`「ユーザーデータが全て削除されます。本当に退会しますか？」`というダイアログボックスを表示させる

予想工数: 3h
