### ISSUE TITLE
ヘッダー修正

### ISSUE THREAD

**Issue by quest-academia** [quest-academia/qa-rails-ec-training-rose#8]
ログイン時、ログアウト時で表示を切り替えること
リンク先ページがあるものについてすべてリンクを有効にすること
ログイン時にヘッダーに名前を表示すること

ページが表示されたらスクリーンショットを保存し、ここに貼り付けて報告すること。

**Comment by yuzumotishun** [comment]
TODO：

- [ ]  ログイン状態、ログアウト状態で表示内容を分ける。（helperのlogged_in?メソッドを使う）
- [ ] リンク先があるものをlink_toで有効化する。
- [ ]  ログイン時にヘッダーに名前を表示する。（current_userから紐付け）


予想対応時間: 2.5h

**Comment by yuzumotishun** [comment]
**１．ログイン状態でヘッダーの表示内容を分けたのが以下のスクショ2枚となります。**

・ログインしていない場合
　　「新規登録、ログイン、ゲストログイン」

・ログインしている場合
　　「商品検索、カート、注文履歴、ユーザ情報、ログアウト」

をヘッダーに表示させています。

【非ログイン時】
![スクリーンショット 2021-08-21 20 24 31](https://user-images.githubusercontent.com/78217764/130320342-af5c5816-9b8b-44c3-a457-521457e2cee7.png)

【ログイン時】
![スクリーンショット 2021-08-21 20 25 02](https://user-images.githubusercontent.com/78217764/130320343-1e48ea82-86cf-4370-9b51-6746c9978075.png)



**2. リンク先があるものをlink_toで有効化する。**

　未マージである「カート」以外はリンクを設定し、カートはTODOとして残しております。



**3. ログインしている場合、ログインしているユーザー名を画面右上に表示させています。**

　ただ、上のスクショ2枚目でもわかるように、seed内でfirst_nameとlast_nameが逆転して作成されてしまっているのでここは修正が必要かと思います。

![スクリーンショット 2021-08-21 20 40 56](https://user-images.githubusercontent.com/78217764/130320593-fc218589-09db-4b13-b3df-44b0d61e2f0c.png)

**Comment by yuki-tachi0219** [comment]
seedも修正したほうがよさそうですね。ご報告ありがとうございます！
