### ISSUE TITLE
ユーザー登録ページ、登録処理

### ISSUE THREAD

**Issue by quest-academia** [quest-academia/qa-rails-ec-training-rose#9]
登録ページ
path: GET /signup
controller#action: Users#new
参考モックアップ: sign_up.html

登録処理
path: POST /signup
controller#action: Users#create

登録後のリダイレクト先については画面定義書参照
登録に成功したら「ユーザーを登録しました。こちらからログインしてください。」というフラッシュメッセージを出すこと
登録に失敗したら、問題箇所を指摘するメッセージを表示すること。ユーザー修正画面と同様に実装すればOK

対応するコントローラとアクションを作成すること
参考モックアップをもとにhtml.erbファイルを作成すること。

**Comment by imai0602** [comment]
## ToDo

- [ ] Usersコントローラーにnewアクションとcreateアクションを追加。

- [ ] views/users/にnew.html.erbをモックアップを参考に登録フォームと登録ボタンの作成し、
登録ページの作成 および 登録処理機能の実装。& `ログインはこちらから`のページ遷移機能を実装。

- [ ] ユーザー登録に成功した場合と失敗した場合で条件分岐を行う。

- 成功した場合、ログイン画面へリダイレクト。ログイン画面にてlayoutsの部分テンプレートを
   使用して成功のフラッシュメッセージを表示

- 失敗した場合、問題箇所を指摘するエラーメッセージをメソッドで取得して表示。

### 確認したいこと
問題箇所を指摘するエラーメッセージ機能は現状ユーザー修正画面には実装できていなかったはずなので、
部分テンプレートを作成して、ユーザー修正機能にも反映したほうが良いでしょうか？

予想工数: 5h
